name: Build App
on:
  push:
jobs:
  build:
    runs-on: macos-12
    steps:
     - uses: actions/checkout@v3
     - name: Set default Xcode 13.4.1
       run: |
         XCODE_ROOT=/Applications/Xcode_13.4.1.app
         echo "MD_APPLE_SDK_ROOT=$XCODE_ROOT" >> $GITHUB_ENV
         sudo xcode-select -s $XCODE_ROOT
     - name: Build App
       run: bash build.sh
     - name: Upload IPA
       uses: actions/upload-artifact@v3
       with:
        name: App
        path: "*.ipa"
